### ISSUE TITLE
Evaluate synthtic script missing

### ISSUE THREAD

**Issue by YuxuanSnow** [r00tman/EventHands#3]
Hello,

i think the evaluation script of synthetic data is missing in this repository.

According to `https://github.com/r00tman/EventHands/blob/main/EVAL_SYNTH.md`, there should be a  `predict_synth.py` file. However, i cannot find it here. Can you please point it our where to find that script?

**Comment by r00tman** [comment]
Thanks for the feedback.
Sorry.
The file was indeed missing. I just uploaded the file to the repository.
